### ISSUE TITLE
Recomendación

### ISSUE THREAD

**Issue by ghost** [borjalor/DroidSentinel#1]
¡Hola!

No sabemos si aún lo habéis investigado, pero imaginamos que, para probar vuestra aplicación vais a tener que hacer un ataque de denegación de servicio, nosotros desde FDist hemos probado LOIC como herramienta para hacerlo, ya que permite hacerlo desde una interfaz y es más sencillo.

Desde el equipo de Trojan - TOTH

**Comment by voar** [comment]
Hola equipo TOTH,

Desde Return0 os damos las gracias por la aportación a nuestro proyecto. Como bien comentabais, la aplicación probada para realizar este tipo de ataques es LOIC. Esta aplicación nos genera tráfico continuo que guardamos con tcpdump en nuestro archivo.

Hemos barajado otros métodos, como por ejemplo utilizar nuestro propio script de bash o utilizar botnets pero finalmente nos hemos decidido por LOIC.

Un saludo
